PruebaNetCore/Controllers/ProductoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PruebaNetCore_AccesoDatos.Datos;
using PruebaNetCore_AccesoDatos.Datos.Repositorio.IRepositorio;
using PruebaNetCore_Modelos;
using PruebaNetCore_Modelos.ViewModels;
using PruebaNetCore_Utilidades;
using System.Data;
using System.IO;
using System.Linq; 

namespace PruebaNetCore.Controllers
{
    [Authorize(Roles = WC.AdminRole)]
    public class ProductoController : Controller
    {
        private readonly IProductoRepositorio _productoRepo;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ProductoController(IProductoRepositorio productoRepo, IWebHostEnvironment webHostEnvironment)
        {
            _productoRepo = productoRepo;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            //IEnumerable<Producto> lista = _db.Producto.Include(c => c.Categoria).Include(t => t.TipoAplicacion);
            IEnumerable<Producto> lista = _productoRepo.ObtenerTodos(incluirPropiedades : "Categoria,TipoAplicacion");
            return View(lista);
        }
        //GET
        public IActionResult Upsert(int? Id)
        {
            //IEnumerable<SelectListItem> categoriaDropDown = _db.Categoria.Select(c=> new SelectListItem { 
            //  Text = c.NombreCategoria,
            //  Value = Id.ToString()
            //});

            //ViewBag.categoriaDropDown = categoriaDropDown;

            //Producto producto = new Producto();

            ProductoVM productoVM = new ProductoVM()
            {
                Producto = new Producto(),
                //CategoriaLista = _db.Categoria.Select(c => new SelectListItem
                //{
                //    Text = c.NombreCategoria,
                //    Value = c.Id.ToString()
                //}),
                //TipoAplicacionLista = _db.TipoAplicacion.Select(c => new SelectListItem
                //{
                //    Text = c.Nombre,
                //    Value = c.Id.ToString()
                //})
                CategoriaLista = _productoRepo.ObtenerTodosDropdownList(WC.CategoriaNombre),
                TipoAplicacionLista = _productoRepo.ObtenerTodosDropdownList(WC.TipoAplicacionNombre)
            };


            if (Id==null)
            {
                return View(productoVM);
            }
            else
            {
                productoVM.Producto = _productoRepo.Obtener(Id.GetValueOrDefault());
                if(productoVM.Producto == null)
                {
                    return NotFound();
                }
                return View(productoVM);
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ProductoVM productoVM)
        {
            if (ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;
                string webRootPatch = _webHostEnvironment.WebRootPath;
                if (productoVM.Producto.Id == 0)
                {
                    //Crear
                    string upload = webRootPatch + WC.ImagenRuta;
                    string fileName = Guid.NewGuid().ToString(); //Es para que se le asigne un Id a la imagen
                    string extension = Path.GetExtension(files[0].FileName);

                    using (var fileStream = new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
                    {
                        files[0].CopyTo(fileStream);//fileStream permite guardar nuestra  imagen
                    } //Todo lo anterior para guardar la imagen
                    productoVM.Producto.ImagenUrl = fileName + extension;
                    _productoRepo.Agregar(productoVM.Producto);
                }
                else
                {
                    //Actualizar
                    var objProducto = _productoRepo.ObtenerPrimero(p => p.Id == productoVM.Producto.Id, isTracking:false);
                    if (files.Count >0) //Se carga una imagen
                    {
                        string upload = webRootPatch + WC.ImagenRuta;
                        string fileName = Guid.NewGuid().ToString(); //Es para que se le asigne un Id a la imagen
                        string extension = Path.GetExtension(files[0].FileName);

                        //borrar la imagen anterior
                        var anteriorFile = Path.Combine(upload, objProducto.ImagenUrl);
                        if (System.IO.File.Exists(anteriorFile))
                        {
                            System.IO.File.Delete(anteriorFile);
                        }
                        //fin borrar imagen anterior
                        using (var fileStream = new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
                        {
                            files[0].CopyTo(fileStream);//fileStream permite guardar nuestra  imagen
                        }

                        productoVM.Producto.ImagenUrl = fileName + extension;
                        //Caso contrario si no se carga una nueva imagen
                    }
                    else
                    {
                        productoVM.Producto.ImagenUrl = objProducto.ImagenUrl;
                    }
                    //Actualiza la base de datos
                    _productoRepo.Actualizar(productoVM.Producto);
                }
                _productoRepo.Grabar();
                return RedirectToAction("Index");
                
            }// If ModeIsValid
             //Se llenan nuevamente las listas si algo falla
             //productoVM.CategoriaLista = _db.Categoria.Select(c => new SelectListItem
             //{
             //    Text = c.NombreCategoria,
             //    Value = c.Id.ToString()
             //});
             //productoVM.TipoAplicacionLista = _db.TipoAplicacion.Select(c => new SelectListItem
             //{
             //    Text = c.Nombre,
             //    Value = c.Id.ToString()
             //});
            productoVM.CategoriaLista = _productoRepo.ObtenerTodosDropdownList(WC.CategoriaNombre);
            productoVM.TipoAplicacionLista = _productoRepo.ObtenerTodosDropdownList(WC.TipoAplicacionNombre);
            return View(productoVM);
        }
        //Get
        public IActionResult Eliminar(int? Id)
        {
            if (Id==null || Id==0)
            {
                return NotFound();
            }
            Producto producto = _productoRepo.ObtenerPrimero(p=> p.Id==Id, incluirPropiedades: "Categoria,TipoAplicacion");
            if(producto== null)
            {
                return NotFound();
            }
            return View(producto);
        }
        // Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Eliminar(Producto producto)
        {
            if(producto == null)
            {
                return NotFound();
            }
            //Eliminar la imagen
            string upload = _webHostEnvironment.WebRootPath + WC.ImagenRuta;
            

            //borrar la imagen anterior
            var anteriorFile = Path.Combine(upload, producto.ImagenUrl);
            if (System.IO.File.Exists(anteriorFile))
            {
                System.IO.File.Delete(anteriorFile);
            }
            //fin Borrar imagen anterior

            _productoRepo.Remover(producto);
            _productoRepo.Grabar();
            return RedirectToAction(nameof(Index));
        }



    }
}

PruebaNetCore/Views/Producto/Eliminar.cshtml
@using PruebaNetCore_Utilidades;
@model PruebaNetCore_Modelos.Producto
@{
    var titulo = "¿Desea Eliminar Producto?";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post" asp-action="Eliminar" >
    <input asp-for="Id" hidden />
    <div class=borde p-3>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="row">
            <h2 class="text-danger">@titulo</h2>
        </div>

        <div class="row">
            <div class="col-8">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            <label asp-for="NombreProducto" class="form-label">Nombre Producto</label>
                            <input asp-for="NombreProducto" disabled class="form-control" />
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <label asp-for="Precio" class="form-label">Precio</label>
                            <input asp-for="Precio" disabled class="form-control" />
                           
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <label asp-for="DescripcionCorta" class="form-label">Descripcion Corta</label>
                            <input asp-for="DescripcionCorta" disabled class="form-control" />
                           
                        </div>
                    </div>

                    <div class="row" hidden>
                        <div class="col-md-6">
                            <label asp-for="DescripcionProducto" class="form-label">Descripcion del Producto</label>
                            <textarea asp-for="DescripcionProducto" class="form-control summernote"></textarea>
                        </div>
                    </div>

                    <div class="row" hidden>
                        <div class="col-md-6">
                            <label asp-for="ImagenUrl" class="form-label">Imagen</label>
                            <input asp-for="ImagenUrl" class="form-control" />
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <label asp-for="TipoAplicacionId" class="form-label">Tipo Aplicacion</label>
                            <input asp-for="TipoAplicacionId" hidden class="form-control" />
                            <input asp-for="TipoAplicacion.Nombre" disabled class="form-control" />
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <label asp-for="CategoriaId" class="form-label">Categoria</label>
                            <input asp-for="CategoriaId" hidden class="form-control" />
                            <input asp-for="Categoria.NombreCategoria" disabled class="form-control" />
                        </div>
                    </div>

                    <br />
                    <div class="d-grid gap-2 d-md-block">
                        <button type="submit" class="btn btn-primary">Eliminar</button>
                        <a asp-controller="Producto" asp-action="Index" class="btn btn-success">Regresar</a>
                    </div>

                </div>
            </div>
            <div class="col-4">
                @if (Model.Id != 0)
                {
                    <img src="@WC.ImagenRuta@Model.ImagenUrl" width="100%" style="border-radius:5px; border:1px solid #bbb" />
                }
            </div>

        </div>

    </div>

</form>

@section Scripts {
    @{
        <parcial name="_ValidationScriptsPartial" />
    }
    
}

PruebaNetCore/Views/Producto/Index.cshtml
@model IEnumerable<PruebaNetCore_Modelos.Producto>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Lista de Productos</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Producto" asp-action="Upsert" class="btn btn-primary ">
                <i class="fa-solid fa-plus"></i>  Nuevo Producto
            </a>
        </div>
    </div>
    <br />
    @if (Model.Count()>0)
    {
        <table class="table table-bordered table-striped " style="width:100%">
            <thead>
                <tr>
                    <th>
                        Nombre
                    </th>
                    <th>
                        Precio
                    </th>
                    <th>
                        Categoria
                    </th>
                    <th>
                        Tipo
                    </th>
                    <th>

                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <th>@item.NombreProducto</th>
                        <th>@item.Precio</th>
                        <th>@item.Categoria.NombreCategoria</th>
                        <th>@item.TipoAplicacion.Nombre</th>
                        <th class="text-center">
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="Producto" asp-action="Upsert" asp-route-Id="@item.Id" class="btn btn-primary mx-2">
                                    <i class="fa-regular fa-pen-to-square"></i>
                                </a>
                                <a asp-controller="Producto" asp-action="Eliminar" asp-route-Id="@item.Id" class="btn btn-danger mx-2">
                                    <i class="fa-solid fa-trash"></i>
                                </a>

                            </div>

                        </th>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>
            No hay registros de Producto
        </p>
    }


</div>

PruebaNetCore/Views/Producto/Upsert.cshtml
@using PruebaNetCore_Utilidades;
@model PruebaNetCore_Modelos.ViewModels.ProductoVM
@{
    var titulo = "Crear Nuevo Producto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post" asp-action="Upsert" enctype="multipart/form-data">
    @if (Model.Producto.Id != 0)
    {
        titulo = "Editar Producto";
        <input asp-for="Producto.Id" hidden/>
    }
    <div class=borde p-3>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="row">
            <h2 class="text-info">@titulo</h2>
        </div>

        <div class="row">
            <div class="col-8">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            <label asp-for="Producto.NombreProducto" class="form-label">Nombre Producto</label>
                            <input asp-for="Producto.NombreProducto" class="form-control"/>
                            <span asp-validation-for="Producto.NombreProducto" class="text-danger"></span>
                        </div> 
                     </div>

                    <div class="row">
                        <div class="col-md-6">
                            <label asp-for="Producto.Precio" class="form-label">Precio</label>
                            <input asp-for="Producto.Precio" class="form-control"/>
                            <span asp-validation-for="Producto.Precio" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <label asp-for="Producto.DescripcionCorta" class="form-label">Descripcion Corta</label>
                            <input asp-for="Producto.DescripcionCorta" class="form-control" />
                            <span asp-validation-for="Producto.DescripcionCorta" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <label asp-for="Producto.DescripcionProducto" class="form-label">Descripcion del Producto</label>
                            <textarea asp-for="Producto.DescripcionProducto" class="form-control summernote"></textarea>
                            <span asp-validation-for="Producto.DescripcionProducto" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <label asp-for="Producto.ImagenUrl" class="form-label">Imagen</label>
                            <input type="file" name="files" id="imagenId" class="form-control" />
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <label asp-for="Producto.TipoAplicacionId" class="form-label">Tipo Aplicacion</label>
                            <select asp-for="Producto.TipoAplicacionId" asp-items="@Model.TipoAplicacionLista" class="form-select">
                                <option disabled selected>--Seleccione un Tipo</option>
                            </select>
                        </div>
                    </div>
                   
                    <div class="row">
                        <div class="col-md-6">
                            <label asp-for="Producto.CategoriaId" class="form-label">Categoria</label>
                            <select asp-for="Producto.CategoriaId" asp-items="@Model.CategoriaLista" class="form-select">
                                <option disabled selected>--Seleccione una categoria</option>
                            </select>
                        </div>
                    </div>

                    <br />
                    <div class="d-grid gap-2 d-md-block">
                        @if(Model.Producto.Id!=0)
                        {
                            <button type="submit" class="btn btn-primary">Actualizar</button>
                        }
                        else
                        {
                            <button type="submit" onclick="return validarImagen()" class="btn btn-primary">Crear Nuevo</button>
                        }
                        <a asp-controller="Producto" asp-action="Index" class="btn btn-success">Regresar</a>
                    </div>

                </div>
             </div>
             <div class="col-4">
                 @if(Model.Producto.Id != 0)
                 {
                    <img src="@WC.ImagenRuta@Model.Producto.ImagenUrl" width="100%" style="border-radius:5px; border:1px solid #bbb" />
                 }
             </div>
             
        </div>

    </div>
    
</form>

@section Scripts {
    @{<parcial name="_ValidationScriptsPartial" />}
    <script>
        $(document).ready(function () {
            $('.summernote').summernote({
                hiight:250
            });
        });
        function validarImagen() {
            if (document.getElementById("imagenId").value==""){
                swal("Error", "Seleccione una Imagen!","error");
                return false;
            }
            return true;
        }
    </script>
}